# Generated by Django 5.1.6 on 2025-02-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geolocation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="geodata",
            name="status",
            field=models.CharField(
                choices=[("SUCCESS", "Success"), ("FAILED", "Failed")],
                default="FAILED",
                max_length=10,
            ),
        ),
    ]
