[mypy]
python_version = 3.13
warn_unused_configs = True
warn_return_any = True
disallow_untyped_defs = True
ignore_missing_imports = True
plugins = mypy_django_plugin.main

exclude = ^manage\.py$

[mypy.plugins.django-stubs]
django_settings_module = "geo_store.settings"
strict_settings = true
